version: '3'

services:
  web:
    build: .
    image: maxazure/xiaohongshu-generator-flask:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///app.db
